use std::fs::File;
use std::io::Write;

pub struct Exporter;

impl Exporter {
    pub fn export_as_header(output_path: &str, name: &str, data: &[(String, usize)]) -> std::io::Result<()> {
        let mut file = File::create(output_path)?;
        writeln!(file, "#pragma once")?;
        writeln!(file, "// Generated by ApkAnalyzer (Rust Edition)")?;
        writeln!(file, "")?;
        writeln!(file, "namespace {} {{", name)?;

        for (item_name, offset) in data {
            let clean_name = item_name.replace(|c: char| !c.is_alphanumeric(), "_");
            writeln!(file, "    constexpr uintptr_t {} = 0x{:x};", clean_name, offset)?;
        }

        writeln!(file, "}}")?;
        Ok(())
    }
}
